TimescaleDB:
  type: PSQL
  user: admin
  database: foggle
  host: 127.0.0.1
  port: 5432
  key: Null

HyperLiquid:
  type: EXCHANGE
  module_name: hl
  port: 50000
  public: '0x7195d5fBC22Afa1FF6A0A25591285Db7a81838D4'
  vault: '0xb22177120b2f33d39770a25993bcb14f2753bae6'
  key: WEB3

IBKR:
  type: EXCHANGE
  module_name: ib
  host: 127.0.0.1
  port: 7496
  clientId: 1

TradingEconomics:
  type: NEWS
  interval: 3600
  topics:
    commodity:
      - crude-oil
      - gold
    united-states:
      - stock-market
      - government-bond-yield
      - inflation-cpi
